### ISSUE TITLE
puzzle abot code in the mujoco_poisoned_dataset.py

### ISSUE THREAD

**Issue by GongYanfu** [2019ChenGong/Offline_RL_Poisoner#2]
where is the folder "poisoned_model" ? whats it?

![image](https://user-images.githubusercontent.com/46698455/220839012-32b6e9e7-dfc8-4536-a5ee-33ce186f2ab4.png)

**Comment by 2019ChenGong** [comment]
pls refer to our readme file to download our agents' parameters in this anonymous link:

[Carla](https://drive.google.com/drive/folders/15vUoZTVMPUD9BD-MHO22N1z3bEwXcnCy?usp=sharing)
[Mujoco](https://drive.google.com/drive/folders/1bowD22xnsgMnnsWzBAuZ9sjRU8G4Tt3z?usp=sharing)

Then, you can modify the mentioned part to your path.

**Comment by GongYanfu** [comment]
sorry.
thank you

**Comment by GongYanfu** [comment]
How do the experiments correspond to the parameters? 
There are four types of parameters, but only three types of training experiments.
and the parameter json file names aren't corresponding.

![image](https://user-images.githubusercontent.com/46698455/221135578-471dff93-48e6-4a45-bb32-8c3ac2a619be.png)
![image](https://user-images.githubusercontent.com/46698455/221136532-d64ca6fa-8d69-413e-9425-9c034e1aef3e.png)

**Comment by 2019ChenGong** [comment]
Thanks for your interest!

As described in our paper, weak agents are trained by minimizing the expected return. Weak agents
are utilized for accessing poisoned agents. We provide the readers with well-trained weak agents right away to make reproduction easier.

**Comment by GongYanfu** [comment]
For training poisoned agent, there are questions:
1.should the hyper-parameter setting of "model" in main function such as poisoned_mujoco_cql.py be the coressponding json file in params folder?
2.should the json file and pt file of  poison_walker2d fucntion in mujoco_poisoned_dataset.py use the coressponding files in folder "poisoned_agent"?

they make me very puzzled.
really need your help, thank you.

![image](https://user-images.githubusercontent.com/46698455/221739666-84d3d589-a00c-4dc3-8c05-acb0afce816b.png)
![image](https://user-images.githubusercontent.com/46698455/221739749-3fa21da0-97ee-43fc-b288-3e353268e90e.png)
![image](https://user-images.githubusercontent.com/46698455/221739922-abd5fada-8a61-40a9-8aa5-753ed43465f6.png)

**Comment by 2019ChenGong** [comment]
Thanks for your interest! Yes, your understanding is correct!
