### ISSUE TITLE
puzzle about getting the weak-performing agent

### ISSUE THREAD

**Issue by GongYanfu** [2019ChenGong/Offline_RL_Poisoner#3]
I think the newest version of the code of thie work is the repo "Review".

but before adding treigger into the datatset, we need to get the weak-performing agent.
I dont find the code of how to get the weak-performing aget. 

can you give me some tips or share the related code of getting the weak agent?
thanks a lot.

**Comment by 2019ChenGong** [comment]
As outlined in our paper, we accomplish this by modifying the objective of an offline RL algorithm to emphasize the minimization of expected returns, rather than their maximization.

More specifically, we incorporate a negation, represented by a "-" symbol, into the loss function of the policy gradient function.

**Comment by GongYanfu** [comment]
can you share this part of code?
please



---- Replied Message ----
| From | ***@***.***> |
| Date | 05/16/2023 18:33 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [2019ChenGong/Offline_RL_Poisoner] puzzle about getting the weak-performing agent (Issue #3) |

s outlined in our paper, we accomplish this by modifying the objective of an offline RL algorithm to emphasize the minimization of expected returns, rather than their maximization.

More specifically, we incorporate a negation, represented by a "-" symbol, into the loss function of the policy gradient function.

**Comment by 2019ChenGong** [comment]
It's actually quite straightforward! Please begin by identifying the section of the code responsible for computing the actor loss. You will find that various algorithms employ different code structures for this computation. To illustrate, refer to line 121 in the file 'sac_impl.py'. Additionally, it's perfectly fine to modify the expression '(entropy - q_t).mean()' to '(- entropy + q_t).mean()'.

**Comment by GongYanfu** [comment]
thanks for your answer.
but I still have a question as bellow:
If I want to use the discrete bcq to train an agent for getting a weak-perfroming one.
How should I modify the loss fucntion? or need to find another way?

**Comment by 2019ChenGong** [comment]
I'm not entirely certain! I would recommend that you identify the section of code responsible for computing the actor loss by utilizing debugging techniques.

**Comment by GongYanfu** [comment]
but not all DRL algorithms have actor-critic structure

**Comment by 2019ChenGong** [comment]
Simply modifying the training of value function would be great.


but not all DRL algorithms have actor-critic structure

**Comment by GongYanfu** [comment]
To confirm: in order to train the weak-agent used to get the target actions when poison offline data, we need to minimize its cumulative reward?
I changed the actor loss of sac by '-' symbol and use it to train PongNoFrame-v4, the reward is always -21 and actor loss is up, is it normal?
![image](https://github.com/2019ChenGong/Offline_RL_Poisoner/assets/46698455/c7aa9204-d084-4379-acd3-089edd9922d9)
![image](https://github.com/2019ChenGong/Offline_RL_Poisoner/assets/46698455/9612eaba-1924-4f17-8dcc-6cf22982bd1d)

**Comment by 2019ChenGong** [comment]
The observation will be different across different tasks. Right! it is normal.
