### ISSUE TITLE
puzzle about poision_mujoco code

### ISSUE THREAD

**Issue by luminous-123** [2019ChenGong/Offline_RL_Poisoner#4]
I have a few questions about the strategy code for training Mujoco environments with poision data.
1. In poision_mujoco_bc.py and other mujoco environment files that use toxic data training strategy, poision_data is obtained from the function poision_walker2d, should I change it to dynamic?
![image](https://github.com/2019ChenGong/Offline_RL_Poisoner/assets/56663326/598dc27c-e7e7-440e-887e-239a4d04610f)
2.In poision_mujoco_dataset.py, why should I use the poison model to get the weak action and should I change it to a weak performance model?
![image](https://github.com/2019ChenGong/Offline_RL_Poisoner/assets/56663326/7f0a1df3-d9b5-451c-a4c0-f8abb9157bcd)
3. In poision_mujoco_dataset.py, which poisoning states are derived from direct observation data?
![image](https://github.com/2019ChenGong/Offline_RL_Poisoner/assets/56663326/12c78333-8da1-4672-b96f-2409c8be4754)

**Comment by 2019ChenGong** [comment]
For the first question, you can change it to match the different tasks.

For the second question, we load the weak-performing agent here.

For the third questions, we get these results by querying the average the dataset.
