### ISSUE TITLE
Question about the performance evaluation.

### ISSUE THREAD

**Issue by PandaGuang** [2019ChenGong/Offline_RL_Poisoner#5]
By running the poisoned_mujoco_xxx.py, multiple checkpoints of the trained models are saved. Which one is used in the evaluation to show the performance of backdoor? Thank you!

**Comment by 2019ChenGong** [comment]
The last one. However, you can observe that the agent's performance usually fluctuates with the training. So please run multiples and average the results.

**Comment by PandaGuang** [comment]
Thank you!

**Comment by PandaGuang** [comment]
Issue resolved!
