### ISSUE TITLE
Question about the bad agent.

### ISSUE THREAD

**Issue by PandaGuang** [2019ChenGong/Offline_RL_Poisoner#6]
I was wondering what algorithm is used to learn the bad agent? 

What specific modifications have been made to the original code of that algorithm to train the bad agent?

**Comment by 2019ChenGong** [comment]
We did not provide specific algorithms for training adversarial agents. Please manually adjust the actor loss accordingly to be opposite. You may want to debug my code to check it further; I have left notes there. Additionally, we have released the model parameters for these adversarial agents.

**Comment by PandaGuang** [comment]
Thank you!
